- hosts: masters
  become: yes
  tasks:
    - name: Start the cluster
      shell: kubeadm init --pod-network-cidr=10.244.0.0/16 >> cluster.txt
      args:
        chdir: $HOME
        creates: cluster.txt

    - name: create .kube directory
      become: yes
      become_user: ubuntu
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/ubuntu/.kube/config
        remote_src: yes
        owner: ubuntu

    - name: install Pod network (calico)
      become: yes
      become_user: ubuntu
      shell: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml >> pod_setup.txt
      args:
        chdir: $HOME
        creates: pod_setup.txt
  
    - name: create manual storage class
      become: yes
      become_user: ubuntu
      shell: |
         cat <<EOF | kubectl apply -f -
         kind: StorageClass
         apiVersion: storage.k8s.io/v1
         metadata:
           name: manual
         provisioner: kubernetes.io/no-provisioner
         volumeBindingMode: WaitForFirstConsumer
         EOF
      
    - name: make manual storage class as default
      become: yes
      become_user: ubuntu
      shell: >
           kubectl patch storageclass manual -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'
    
    - name: create data folder
      become: yes
      become_user: ubuntu
      file:
        path: /home/ubuntu/data
        state: directory
    
    - name: create volume
      become: yes
      become_user: ubuntu
      shell: |
         cat <<EOF | kubectl apply -f -
         apiVersion: v1
         kind: PersistentVolume
         metadata:
           name: manualpv
         spec:
           storageClassName: manual
           capacity:
             storage: 1Gi
           accessModes:
           - ReadWriteOnce
           hostPath:
             path: /home/ubuntu/data
         EOF