whisk:
  ingress:
    type: NodePort
    apiHostName: {{CLUSTER_IP}}
    apiHostPort: 31001

nginx:
  httpsNodePort: 31001

invoker:
  containerFactory:
    impl: "kubernetes"

k8s:
  persistence:
    enabled: false